testingWebApi/mvcDotNetTrainingGround/Models/CreateNewDeveloperViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace mvcDotNetTrainingGround.Models;

public class CreateNewDeveloperViewModel
{
    [DisplayName("Developer Name")]
    [Required]
    public string? Name { get; set; }

    [DisplayName("Email Address")]
    [Required]
    [EmailAddress]
    public string? Email { get; set; }

}

testingWebApi/mvcDotNetTrainingGround/Models/Developer.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace mvcDotNetTrainingGround.Models;

public class Developer
{
    [Required(ErrorMessage = "Id is required.")]
    public int? Id { get; set; }

    [Required(ErrorMessage = "Name is required.")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Email is required.")]
    public string? Email { get; set; }

}

testingWebApi/mvcDotNetTrainingGround/Models/ErrorViewModel.cs
namespace mvcDotNetTrainingGround.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}


testingWebApi/mvcDotNetTrainingGround/Controllers/DevelopersController.cs
using Microsoft.AspNetCore.Mvc;
using mvcDotNetTrainingGround.Models;
namespace mvcDotNetTrainingGround.Controllers;

public class DevelopersController : Controller
{
    public class Db
    {
        public Db()
        {
            Developers = new List<Developer> {
            new Developer() { Id = 1, Name = "Miele", Email = "miele@student.com"},
            new Developer() { Id = 2, Name = "Matte", Email = "matte@student.com"},
        };
        }
        public List<Developer> Developers { get; set; }
    }


    private Db _db;
    public DevelopersController(Db db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        return View(_db.Developers);
    }

    public IActionResult Details(int id)
    {
        return View(_db.Developers.Find(d => d.Id == id));
    }


    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(CreateNewDeveloperViewModel viewModel)
    {

        var nextId = _db.Developers.Count + 1;
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }
        else
        {

            var developerToAdd = new Developer()
            {
                Id = nextId,
                Name = viewModel.Name,
                Email = viewModel.Email,
            };

            _db.Developers.Add(developerToAdd);
        }

        return RedirectToAction(nameof(Index));

    }
}

testingWebApi/mvcDotNetTrainingGround/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvcDotNetTrainingGround.Models;

namespace mvcDotNetTrainingGround.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

testingWebApi/mvcDotNetTrainingGround/Views/Developers/Create.cshtml
@model CreateNewDeveloperViewModel

<h1>Create a new developer!</h1>
<form asp-controller="Developers" asp-action="Create" method="post">
    @Html.DisplayNameFor(m => m.Name): @Html.TextBoxFor(m => m.Name)
    <br />
    <br />
    @Html.DisplayNameFor(m => m.Email): @Html.TextBoxFor(m => m.Email)
    <br />
    <br />
    <button type="submit">Create a new developer</button>
</form>

<a asp-controller="Developers" asp-action="Index">
    Back to Home
</a>

testingWebApi/mvcDotNetTrainingGround/Views/Developers/Details.cshtml
@model Developer


<h1>@Model.Name</h1>
<ul>
    <li>@Html.DisplayNameFor(m => m.Id): @Model.Id</li>
    <li>@Html.DisplayNameFor(m => m.Name): @Model.Name</li>
    <li>@Html.DisplayNameFor(m => m.Email): @Model.Email</li>
</ul>

<a asp-controller="Developers" asp-action="Index">
    Back to Home
</a>

testingWebApi/mvcDotNetTrainingGround/Views/Developers/Index.cshtml
@model List<Developer>
<link href="Index.cshtml.css" rel="stylesheet">

<h1>Showing @Model.Count developers!</h1>

<table style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    @for (var i = 0; i < @Model.Count; i++)
    {
        if (i % 2 != 0)
        {
            <tr class="background">
                <td>@Model[i].Name</td>
                <td>@Model[i].Email</td>
                <td>
                    <a asp-controller="Developers" asp-action="Details" asp-route-id=@Model[i].Id>
                        Details
                    </a>
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td>@Model[i].Name</td>
                <td>@Model[i].Email</td>
                <td>
                    <a asp-controller="Developers" asp-action="Details" asp-route-id=@Model[i].Id>
                        Details
                    </a>
                </td>
            </tr>
        }
    }

</table>
<br />
<a asp-controller="Developers" asp-action="Create">Create a new developer</a>

testingWebApi/mvcDotNetTrainingGround/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcDotNetTrainingGround</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvcDotNetTrainingGround.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvcDotNetTrainingGround</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - mvcDotNetTrainingGround - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>